- name: copy mongo repo files
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Replace listening address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Make sure mongodb service is running
  ansible.builtin.systemd_service:
    state: restarted
    name: mongod
    enabled: true
    daemon_reload: yes