- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed


- name: Remove old httpd content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create Http directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

#- name: Download frontend content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html/
#    remote_src: yes

- name: Download {{component}} content
  ansible.builtin.unarchive:
    src: http://admin:admin123@172.31.88.150:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: copy Nginx config file to destination
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy Roboshop config file to destination
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Make sure nginx service is running
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true
    daemon_reload: yes