- name: Disable mysql
  ansible.builtin.shell: dnf module disable mysql -y

- name: copy mysql repo files
  ansible.builtin.template:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install mysql
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Make sure mysql service is running
  ansible.builtin.systemd_service:
    state: restarted
    name: mysqld
    enabled: true
    daemon_reload: yes

- name: change mysql passowrd
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
