- name: Disable nodejs10 enable nodejs18
  ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

#- name:  enable nodejs18
#  ansible.builtin.shell: dnf module enable nodejs:18


- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Add Roboshop User
  ansible.builtin.user:
    name: roboshop

- name: Remove old app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create an Application directory
  ansible.builtin.file:
    path: /app
    state: directory




- name: Download frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm:
    path: /app
    state: latest

- name: copy service file to destination
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Make sure nginx service is running
  ansible.builtin.systemd_service:
    state: restarted
    name: catalogue
    enabled: true
    daemon_reload: yes

- name: Install mongo client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: load schema
  ansible.builtin.shell: mongo --host mongodb-dev.pappik.online </app/schema/catalogue.js
