- name: Add Roboshop User
  ansible.builtin.user:
    name: roboshop

- name: Remove old app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create an Application directory
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Download {{component}} content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

- name: Download {{component}} content
  ansible.builtin.unarchive:
    src: http://admin:admin123@172.31.88.150:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes