- name: Stop the application
  ansible.builtin.systemd:
    name: "{{component}}"
    state: stopped

- name: app prereq
  ansible.builtin.include_tasks: "appreq.yml"

- name: Start the  application
  ansible.builtin.systemd:
    name: "{{component}}"
    state: started