- name: set hostname
  ansible.builtin.shell: set-hostname {{component}}

- name: Install Prometheus Node Exporter
  ansible.builtin.shell: labauto prometheus-node-exporter


- name: Copy Prometheus Alerts conf to prometheus server
  ansible.builtin.shell: sshpass -p DevOps321 scp /tmp/alert.yml root@172.31.37.7:/opt/prometheus/alerts/{{component}}.yml

- name: Reload Prometheus
  ansible.builtin.shell: curl -s -XPOST http://172.31.37.7:9090/-/reload

- name: Setup Prometheus Alerts Config
  ansible.builtin.template:
    src: alert.yml
    dest: /tmp/alert.yml

#    Grafana Dashboard
- name: Make Template
  ansible.builtin.template:
    src: grafana-template.json
    dest: /tmp/grafana.json
    remote_src: yes

- name: Import Grafana dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://172.31.37.7:3000
    grafana_api_key: "{{ lookup('aws_ssm', 'grafana_api_key', region='us-east-1' ) }}"
    state: present
    overwrite: yes
    path: /tmp/grafana.json