- name: copy mongo repo files
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
  when: schema_load

- name: Install mongo client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed
  when: schema_load


#- name: load schema
#  ansible.builtin.shell: mongo --host mongodb-dev.pappik.online </app/schema/{{component}}.js
#  when: schema_load

- name: Load Schema
  ansible.builtin.shell: mongo --ssl --host dev-docdb-cluster.cluster-ca9sdnry65dv.us-east-1.docdb.amazonaws.com:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username {{ lookup('aws_ssm', "{{env}}.docdb.DB_ADMIN_USER", region='us-east-1' ) }} --password {{ lookup('aws_ssm', "{{env}}.docdb.DB_ADMIN_PASS", region='us-east-1' ) }}
