- name: Disable nodejs10 enable nodejs18
  ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App prereq task
  ansible.builtin.include_tasks: "appreq.yml"

- name: install dependencies
  community.general.npm:
    path: /app
    state: latest

- name: App prereq task
  ansible.builtin.include_tasks: "systemd.yml"

- name: App prereq task
  ansible.builtin.include_tasks: "mongo_schema.yml"

