route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: "email"
    email_configs:
      - to: "prema.paparao75@gmail.com"      # you@example.com
        from: "prema.paparao75@gmail.com"  # alertmanager@example.com
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
        auth_username: "AKIAYR7KK3UFCVTTA7NV"
        auth_password: "BFWqnA9SF+2mtN6cebt+/FVJ1uHAzK1Mit6/KFmD074c"
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
